### ISSUE TITLE
Syntax issue with examples in documentation 

### ISSUE THREAD

**Issue by arashmolavi** [gnomikos/traIXroute#3]
Hi George,

Awesome tool! I just cloned your repo and playing around with it, starting with examples in your doc, but they all throw syntax errors! I was wondering if there is a newer version of the doc available? 

Specifically, I am interested in running probes with scamper options. I managed to make it work using the following command:

 `sudo python3 traIXroute.py probe -s "-P TCP" -dest google.com`

Does this look right to you?

**Comment by gnomikos** [comment]
Hi,

thank you for your comments. Take care to clone the last version (2.0). The syntax errors might happen because you try to use the previous command line format. The last version of documentation has the "2.0" tag and it's located in /Documentation of v.2.0 branch. I think, probably, it's a good idea to clean the repository keeping only the last version.

For example to use traIXroute with defaults and scamper you can run:
python3 traIXroute.py probe -dest inspire.edu.gr -s

if you want to configure scamper with certain arguments you can try:
python3 traIXroute.py probe -dest inspire.edu.gr -s="-m 12"

Of course, your command has no problem. You have set the destination _-dest google.com_ using _scamper_ with arguments "-P TCP"

**Comment by arashmolavi** [comment]
Thanks George. You were right, I was looking at v1.0's doc. Thank you :)

**Comment by gnomikos** [comment]
Ok nice!! Btw, keep in touch, the next few days, I am going to release the next version 2.1 resolving some bugs and introducing the Remote Peering mechanism based on this project: http://www.inspire.edu.gr/rp/about.html

This means that traIXroute will be able to discriminate the IXP crossing links based on remote peering.

-G
